// Date: 28/08/2015 11:11:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package Com.gun.Model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class glock17Model extends ModelBase
{
  //fields
    ModelRenderer endppiece;
    ModelRenderer detail1;
    ModelRenderer detail2;
    ModelRenderer above_clip_piecel;
    ModelRenderer endpiece;
    ModelRenderer endpiecesider;
    ModelRenderer endpiecesidel;
    ModelRenderer endpiecesideb;
    ModelRenderer endpiecesidef;
    ModelRenderer above_clip_piece;
    ModelRenderer above_clip_pieceb;
    ModelRenderer above_clip_piecer;
    ModelRenderer above_clip_piecef;
    ModelRenderer front_barrel;
    ModelRenderer back_barrel;
    ModelRenderer triger;
    ModelRenderer barrel;
    ModelRenderer trigergaurd;
    ModelRenderer trigergaurd2;
    ModelRenderer trigergaurd3;
  
  public glock17Model()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      endppiece = new ModelRenderer(this, 24, 47);
      endppiece.addBox(15.2F, 0.5F, 0.5F, 1, 2, 2);
      endppiece.setRotationPoint(0F, 0F, 0F);
      endppiece.setTextureSize(128, 64);
      endppiece.mirror = true;
      setRotation(endppiece, 0F, 0F, 0F);
      detail1 = new ModelRenderer(this, 6, 45);
      detail1.addBox(0F, 0F, 0F, 3, 5, 1);
      detail1.setRotationPoint(1.2F, 4F, -0.2F);
      detail1.setTextureSize(128, 64);
      detail1.mirror = true;
      setRotation(detail1, 0F, 0F, 0.2230717F);
      detail2 = new ModelRenderer(this, 6, 45);
      detail2.addBox(0F, 0F, 0F, 3, 5, 1);
      detail2.setRotationPoint(1.2F, 4F, 2.2F);
      detail2.setTextureSize(128, 64);
      detail2.mirror = true;
      setRotation(detail2, 0F, 0F, 0.2230717F);
      above_clip_piecel = new ModelRenderer(this, 100, 44);
      above_clip_piecel.addBox(0F, 0F, 0F, 1, 1, 0);
      above_clip_piecel.setRotationPoint(1F, -0.2F, 2.5F);
      above_clip_piecel.setTextureSize(128, 64);
      above_clip_piecel.mirror = true;
      setRotation(above_clip_piecel, 0F, 0F, 0F);
      endpiece = new ModelRenderer(this, 100, 44);
      endpiece.addBox(0F, 0F, 0F, 1, 0, 1);
      endpiece.setRotationPoint(14F, -0.2F, 1F);
      endpiece.setTextureSize(128, 64);
      endpiece.mirror = true;
      setRotation(endpiece, 0F, 0F, 0F);
      endpiecesider = new ModelRenderer(this, 100, 46);
      endpiecesider.addBox(0F, 0F, 0F, 1, 1, 0);
      endpiecesider.setRotationPoint(14F, -0.2F, 1F);
      endpiecesider.setTextureSize(128, 64);
      endpiecesider.mirror = true;
      setRotation(endpiecesider, 0F, 0F, 0F);
      endpiecesidel = new ModelRenderer(this, 100, 46);
      endpiecesidel.addBox(0F, 0F, 0F, 1, 1, 0);
      endpiecesidel.setRotationPoint(14F, -0.2F, 2F);
      endpiecesidel.setTextureSize(128, 64);
      endpiecesidel.mirror = true;
      setRotation(endpiecesidel, 0F, 0F, 0F);
      endpiecesideb = new ModelRenderer(this, 100, 46);
      endpiecesideb.addBox(0F, 0F, 0F, 0, 1, 1);
      endpiecesideb.setRotationPoint(14F, -0.2F, 1F);
      endpiecesideb.setTextureSize(128, 64);
      endpiecesideb.mirror = true;
      setRotation(endpiecesideb, 0F, 0F, 0F);
      endpiecesidef = new ModelRenderer(this, 100, 44);
      endpiecesidef.addBox(0F, 0F, 0F, 0, 1, 1);
      endpiecesidef.setRotationPoint(15F, -0.2F, 1F);
      endpiecesidef.setTextureSize(128, 64);
      endpiecesidef.mirror = true;
      setRotation(endpiecesidef, 0F, 0F, 0F);
      above_clip_piece = new ModelRenderer(this, 100, 44);
      above_clip_piece.addBox(0F, 0F, 0F, 1, 0, 2);
      above_clip_piece.setRotationPoint(1F, -0.2F, 0.5F);
      above_clip_piece.setTextureSize(128, 64);
      above_clip_piece.mirror = true;
      setRotation(above_clip_piece, 0F, 0F, 0F);
      above_clip_pieceb = new ModelRenderer(this, 100, 44);
      above_clip_pieceb.addBox(0F, 0F, 0F, 0, 1, 2);
      above_clip_pieceb.setRotationPoint(1F, -0.2F, 0.5F);
      above_clip_pieceb.setTextureSize(128, 64);
      above_clip_pieceb.mirror = true;
      setRotation(above_clip_pieceb, 0F, 0F, 0F);
      above_clip_piecer = new ModelRenderer(this, 100, 44);
      above_clip_piecer.addBox(0F, 0F, 0F, 1, 1, 0);
      above_clip_piecer.setRotationPoint(1F, -0.2F, 0.5F);
      above_clip_piecer.setTextureSize(128, 64);
      above_clip_piecer.mirror = true;
      setRotation(above_clip_piecer, 0F, 0F, 0F);
      above_clip_piecef = new ModelRenderer(this, 100, 44);
      above_clip_piecef.addBox(0F, 0F, 0F, 0, 1, 2);
      above_clip_piecef.setRotationPoint(2F, -0.2F, 0.5F);
      above_clip_piecef.setTextureSize(128, 64);
      above_clip_piecef.mirror = true;
      setRotation(above_clip_piecef, 0F, 0F, 0F);
      front_barrel = new ModelRenderer(this, 63, 32);
      front_barrel.addBox(0F, 0F, 0.5F, 6, 1, 2);
      front_barrel.setRotationPoint(10F, 3F, 0F);
      front_barrel.setTextureSize(128, 64);
      front_barrel.mirror = true;
      setRotation(front_barrel, 0F, 0F, 0F);
      back_barrel = new ModelRenderer(this, 60, 32);
      back_barrel.addBox(0F, 0F, 0F, 9, 1, 3);
      back_barrel.setRotationPoint(1F, 3F, 0F);
      back_barrel.setTextureSize(128, 64);
      back_barrel.mirror = true;
      setRotation(back_barrel, 0F, 0F, 0F);
      triger = new ModelRenderer(this, 58, 44);
      triger.addBox(0F, 0F, 0F, 1, 1, 1);
      triger.setRotationPoint(5F, 4F, 1F);
      triger.setTextureSize(128, 64);
      triger.mirror = true;
      setRotation(triger, 0F, 0F, 0F);
      barrel = new ModelRenderer(this, 41, 25);
      barrel.addBox(0F, 0F, 0F, 16, 3, 3);
      barrel.setRotationPoint(0F, 0F, 0F);
      barrel.setTextureSize(128, 64);
      barrel.mirror = true;
      setRotation(barrel, 0F, 0F, 0F);
      trigergaurd = new ModelRenderer(this, 83, 43);
      trigergaurd.addBox(0F, 0F, 2F, 3, 1, 1);
      trigergaurd.setRotationPoint(4F, 6F, -1F);
      trigergaurd.setTextureSize(128, 64);
      trigergaurd.mirror = true;
      setRotation(trigergaurd, 0F, 0F, 0F);
      trigergaurd2 = new ModelRenderer(this, 68, 37);
      trigergaurd2.addBox(0F, 0F, 0F, 4, 7, 3);
      trigergaurd2.setRotationPoint(1F, 3F, 0F);
      trigergaurd2.setTextureSize(128, 64);
      trigergaurd2.mirror = true;
      setRotation(trigergaurd2, 0F, 0F, 0.2230717F);
      trigergaurd3 = new ModelRenderer(this, 71, 50);
      trigergaurd3.addBox(0F, 0F, 0F, 1, 3, 1);
      trigergaurd3.setRotationPoint(6.5F, 3F, 1F);
      trigergaurd3.setTextureSize(128, 64);
      trigergaurd3.mirror = true;
      setRotation(trigergaurd3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    endppiece.render(f5);
    detail1.render(f5);
    detail2.render(f5);
    above_clip_piecel.render(f5);
    endpiece.render(f5);
    endpiecesider.render(f5);
    endpiecesidel.render(f5);
    endpiecesideb.render(f5);
    endpiecesidef.render(f5);
    above_clip_piece.render(f5);
    above_clip_pieceb.render(f5);
    above_clip_piecer.render(f5);
    above_clip_piecef.render(f5);
    front_barrel.render(f5);
    back_barrel.render(f5);
    triger.render(f5);
    barrel.render(f5);
    trigergaurd.render(f5);
    trigergaurd2.render(f5);
    trigergaurd3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
